apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc-new
  namespace: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ebs-sc-gp3
