apiVersion: v1
kind: Secret
metadata:
  name: keycloak-tls-secret
  namespace: keycloak
type: kubernetes.io/tls
data:
  tls.crt: <base 64 your public key tls.crt>
  tls.key: <base 64 your private key tls.key>
