apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
  namespace: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0
          args: ["start", "--cache-stack=kubernetes"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            #- name: KC_HTTPS_CERTIFICATE_FILE
            #  value: "/etc/certs/tls.crt"
            #- name: KC_HTTPS_CERTIFICATE_KEY_FILE
            #  value: "/etc/certs/tls.key"
            - name: KC_HOSTNAME
              value: "auth.keycloak.me"
            - name: KC_PROXY
              value: "edge"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://database-1.c6royoums8vm.us-east-1.rds.amazonaws.com:5432/keycloakdbrds"
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: db-username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: db-password
            - name: jgroups.dns.query
              value: keycloak
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: false"
            - name: KC_DB_POOL_INITIAL_SIZE
              value: "5"
            - name: KC_DB_POOL_MIN_SIZE
              value: "5"
            - name: KC_DB_POOL_MAX_SIZE
              value: "20"
            - name: KC_TRANSACTION_XA_ENABLED
              value: "false"
            - name: KC_HEALTH_ENABLED
              value: "true"
            #- name: KC_HOSTNAME_ADMIN_URL
            #  value: "https://auth.keycloak.me"
            #- name: KC_HOSTNAME_URL
            #  value: "https://auth.keycloak.me"

          #volumeMounts:
          #  - name: certs
          #    mountPath: "/etc/certs"
          #    readOnly: true
          ports:
            #- name: jgroups
            #  containerPort: 7600
            - name: https
              containerPort: 8443
            - name: http
              containerPort: 8080
          startupProbe:
              httpGet:
                path: /health/ready
                port: 9000
                scheme: HTTP
              initialDelaySeconds: 60
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 30   # 30 x 10s = 5 phút
          readinessProbe:
              httpGet:
                path: /health/ready
                port: 9000
                scheme: HTTP
              initialDelaySeconds: 60
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 6    # 6 x 10s = 1 phút
          livenessProbe:
              httpGet:
                path: /health/live
                port: 9000
                scheme: HTTP
              initialDelaySeconds: 120
              periodSeconds: 30
              timeoutSeconds: 5
              failureThreshold: 5
      #volumes:
      #  - name: certs
      #    secret:
      #      secretName: keycloak-tls-secret
      #      items:
      #        - key: tls.crt
      #          path: tls.crt
      #        - key: tls.key
      #          path: tls.key
