apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1

  db:
    vendor: postgres
    host: postgres-db
    port: 5432
    database: keycloak
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password

  http:
    httpEnabled: true
    httpPort: 8080

  hostname:
    hostname: ""          # POC, no strict hostname
    strict: false
    strictBackchannel: false

  # turn off HTTPS requirement
  additionalOptions:
    - name: spi-hostname-default-ssl-required
      value: "NONE"
    - name: hostname-strict
      value: "false"
    - name: hostname-strict-https
      value: "false"

  #podDisruptionBudget:
  #  enabled: false
