apiVersion: v1
kind: Service
metadata:
  name: keycloak-nodeport
  namespace: keycloak
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: keycloak
  ports:
    - name: http
      port: 8080          # port bên trong cluster
      targetPort: 8080    # port trong container Keycloak
      nodePort: 30080     # port ngoài EC2 (bạn có thể đổi)
