apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # use PV static, not use StorageClass dynamic
  hostPath:
    path: /home/ec2-user/data/postgres-keycloak
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""   # should be match with above
  resources:
    requests:
      storage: 1Gi
  volumeName: postgres-data-pv
