{{- if .Values.operator.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.operator.fullnameOverride | default "keycloak-operator" }}-role
  namespace: {{ .Values.operator.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.operator.nameOverride | default "keycloak-operator" }}
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get","list","watch","create","delete","patch","update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get","list","watch"]

  - apiGroups: [""]
    resources: ["secrets","services"]
    verbs: ["get","list","watch","create","delete","patch","update"]
  
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get","list","watch","create","delete","patch","update"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","list","watch","create","delete","patch","update"]
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["servicemonitors"]
    verbs: ["get","list","watch","create","delete","update"]
{{- end }}
