{{- if .Values.operator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.operator.fullnameOverride | default "keycloak-operator" }}
  namespace: {{ .Values.operator.namespace }}
{{- end }}
